#!/usr/bin/env php
<?php
namespace beaver;
require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;

$application = new Application();

# add our commands
$application->add(new MakeCommand());
$application->add(new MakeBlocks());

$application->run();