#!/usr/bin/env php
<?php
namespace beaver;
require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
$application = new Application();

# add our commands
$loader = new \Twig\Loader\FilesystemLoader('template');
$application->add(new MakeCommand(new \Twig\Environment($loader)));

$application->run();